---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: dep1
  name: disney-hotstar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dep1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dep1
    spec:
      containers:
      - image: abhaypande/disney-hotstar
        name: disney-hotstar-container
---
---
apiVersion: v1
kind: Service
metadata:
  name: disney-hotstar
spec:
  selector:
    app: dep1
  ports:
  - nodePort: 30000
    port: 3000
    targetPort: 3000
  type: NodePort
