---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: disney
  name: disney
spec:
  replicas: 1
  selector:
    matchLabels:
      app: disney
  template:
    metadata:
      labels:
        app: disney
    spec:
      containers:
      - name: disney-container
        image: abhaypande/disney-hotstar
---
---
apiVersion: v1
kind: Service
metadata:
  name: disney-hotstar
spec:
  selector:
    app: dep1
  ports:
  - nodePort: 30000
    port: 3000
    targetPort: 3000
  type: NodePort
